version: 2.1

jobs:
 build:
  docker:
    - image: circleci/openjdk:11-jdk

  steps:
    - checkout
    - run:
       name: Build Java App
       command: |
         # build command
         ./gradlew build